### ISSUE TITLE
Client-initiated capacity update

### ISSUE THREAD

**Issue by dklimkin** [youtube/doorman#8]
Feature request.

For some use cases it would be great to have an option for a client-initiated capacity update.

E.g. despite of being granted a lease, the target service returns some "rate exceeded" error. A Doorman client knows that but there is no way [I found] to notify the Doorman server of it, and to shrink the quotas for other clients using the same target service.

**Comment by anhldbk** [comment]
@dklimkin So what you mean is: in addition to `global capacity`, we must have a `local capacity` for each client?

**Comment by dklimkin** [comment]
I have to say I completely lost the context here in the two years passed.
